device = "/dev/video0"
width = 640
height = 480
framerate = "30/1"
bitrate = 1000
key = "literal:f2cb28de75655c20b8f95aa7c08c545011aff408c95ce64964ff9c992c6fc0a5"
output_path = "output.ts.enc"
cv_enabled = false
